{{- if and (not .Values.existingSecret) .Values.config.providers.openweathermap.enabled .Values.config.providers.openweathermap.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weather-exporter.fullname" . }}
  labels:
    {{- include "weather-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  openweathermap-api-key: {{ .Values.config.providers.openweathermap.apiKey | quote }}
{{- end }}
