replicaCount: 1

image:
  repository: ghcr.io/joluc/weather-exporter
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 9798

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

config:
  cities:
    - "Leipzig:51.33,12.37"

  providers:
    dwd:
      enabled: false
    yr:
      userAgent: ""
    openweathermap:
      enabled: false
      apiKey: ""

  jsonLogs: false
  listenAddress: ":9798"

# Use existing secret instead of creating one
existingSecret: ""
